### ISSUE TITLE
Wrong feature `INST`

### ISSUE THREAD

**Issue by kbatsuren** [unimorph/kat#1]
@davidgu13, thanks for the update. 

The feature `INST` should be `INS`. `um-canonicalize` tool didn't throw any other error. Could you also leave the comments about language specifics?

You can see the language-specific notes here. https://github.com/unimorph/got

Huygaa

**Comment by davidgu13** [comment]
Hello Huygaa,

Apparently this feature is reminiscent of the old dataset -- I contributed the new verbs samples, not the nouns & adjectives.
Anyway, I replaced it with INS and added Language-Specific details (and also extended the stats section).

Thank you!
David
